#-----------------------------------------------------------------------------
# Perl source generated by wxDesigner from file: photo_exif.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

use Wx;
use strict;

use Wx qw( wxDefaultSize wxDefaultPosition wxID_OK wxID_SAVE wxID_SAVEAS wxID_CANCEL wxID_YES wxID_EXIT wxID_ABOUT wxID_HELP );
use Wx qw( wxVERTICAL wxHORIZONTAL wxALL wxLEFT wxRIGHT wxTOP wxBOTTOM wxCENTRE wxGROW wxADJUST_MINSIZE );
use Wx qw( wxALIGN_RIGHT wxALIGN_BOTTOM wxALIGN_CENTER wxALIGN_CENTER_VERTICAL wxALIGN_CENTER_HORIZONTAL );


# Bitmap functions

use Wx qw( wxNullBitmap wxBITMAP_TYPE_PNG );

# Window functions

use vars qw($ID_TEXT); $ID_TEXT = 10000;
use vars qw($ID_EXIF_CREATE_DATE); $ID_EXIF_CREATE_DATE = 10001;
use vars qw($ID_EXIF_WIDTH); $ID_EXIF_WIDTH = 10002;
use vars qw($ID_EXIF_HEIGHT); $ID_EXIF_HEIGHT = 10003;
use vars qw($ID_EXIF_ORIENTATION); $ID_EXIF_ORIENTATION = 10004;
use vars qw($ID_EXIF_ISO); $ID_EXIF_ISO = 10005;
use vars qw($ID_EXIF_SHUTTER_SPEED); $ID_EXIF_SHUTTER_SPEED = 10006;
use vars qw($ID_EXIF_APERTURE); $ID_EXIF_APERTURE = 10007;
use vars qw($ID_EXIF_FOCAL_LENGTH); $ID_EXIF_FOCAL_LENGTH = 10008;
use vars qw($ID_EXIF_MODEL); $ID_EXIF_MODEL = 10009;
use vars qw($ID_EXIF_LENS); $ID_EXIF_LENS = 10010;

sub PhotoExif {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = Wx::FlexGridSizer->new( 0, 2, 0, 0 );
    
    my( $item2 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Create date :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item2, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item3 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_CREATE_DATE, "", wxDefaultPosition, [100,-1], 0 );
    $item1->AddWindow( $item3, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item4 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Width :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item5 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_WIDTH, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item6 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Height :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item7 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_HEIGHT, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item8 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Orientation :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item9 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_ORIENTATION, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item9, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item10 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "ISO :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item11 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_ISO, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item12 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Shutter speed :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item13 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_SHUTTER_SPEED, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item13, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item14 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Aperture :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item14, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item15 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_APERTURE, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item15, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item16 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Focal length :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item16, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item17 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_FOCAL_LENGTH, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item17, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item18 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Model :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item18, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item19 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_MODEL, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item19, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item20 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Lens :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item20, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item21 ) = Wx::StaticText->new( $_[0], $main::ID_EXIF_LENS, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item21, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    $item0->Add( $item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

# Menu bar functions


# Toolbar functions


# End of generated file
