<?php
// Misc Options section
$lang['UAM_miscTitle_d'] = '
- Registered users monitoring<br/>
- Nickname mandatory for guests comments<br/>
...
';
$lang['UAM_Admins_Copy_d'] = 'By enabling this option, all administrators of the gallery will receive a copy of <b style=&quot;color: red;&quot;>all emails</b> sent by the plugin. This can be usefull to check if emails are really sent and to keep a copy in case of dispute. For example, during a registration validation or renewal.<br/><br/>Subjects of copied emails are prefixed with <b style=&quot;color: green;&quot;>&quot;[Admins Copy] - &quot;</b>';
$lang['UAM_infomailTitle_d'] = 'This option allows to automate sending an information email to a user when he changes his password or email address in his profile page.<br/><br/>
The content of the message sent is composed of a customizable part to introduce a little welcome note and a fixed part indicating the login name, password and email address of the user.';
$lang['UAM_HidePasswTitle_d'] = 'Choose here if you want to display the password chosen by the visitor in the information email. If you enable the option, the password will then appear in clear text. If you disable the password will not appear at all.';
$lang['UAM_MailInfo_Subject_d'] = 'Enter here your customized information email subject.<br/>
By default, the field has a generic text in English but you can change it and use the translation tags [lang =?] of the Extended Description plugin if installed.
<br/><br/>
The following additional customizations tags are available without using the Extended Description plugin:<br/>
- <b style=&quot;color: red;&quot;>[username]</b> to automatically insert the name of the destination user of the email.<br/>
- <b style=&quot;color: red;&quot;>[mygallery]</b> to insert the title of your gallery.<br/>
';
$lang['UAM_infotxtTitle_d'] = 'Enter the introductory text that you want to appear in the information email.
<br/><br/>
Further customize the content with special inserted tags:<br/>
- <b style=&quot;color: red;&quot;>[username]</b> to automatically insert the name of the destination user of the email.<br/>
- <b style=&quot;color: red;&quot;>[mygallery]</b> to insert the title of your gallery.<br/>
- <b style=&quot;color: red;&quot;>[myurl]</b> to insert your gallery URL if set in Piwigo\'s configuration options.
<br/><br/>
To use multiple languages, you can use the Extended description plugin\'s tags if it is active.';
$lang['UAM_AddURL2Mail_d'] = 'Enabling this option will add the URL of your gallery at the end of emails generated by the plugin, like a signature.';
$lang['UAM_Tracking registered users_d'] = 'This activates a table in the &quot;Tracking registered users&quot; tab where are listed registered users on the gallery with the date of their last visit and time spent (in days) since their last visit. Monitoring is purely informative for the administrator of the gallery.';
$lang['UAM_RedirTitle_d'] = 'This option automatically redirect a registered user to his customization page only at his first connection to the gallery.<br/><br/>
Please note: This feature does not apply to all registered users. Those with &quot;admin&quot;, &quot;webmaster&quot; or &quot;generic&quot; status are excluded.';
$lang['UAM_CustomPasswRetrTitle_d'] = 'By default, when a user has lost his password and selects the option of recovery, he receives an email containing only his username and his new password.
<br/><br/>
Here, you can add text of your choice to be inserted <b><u>before</u></b> the standard information.
<br/><br/>
Further customize the content with special inserted tags:<br/>
- <b style=&quot;color: red;&quot;>[mygallery]</b> to insert the title of your gallery.<br/>
- <b style=&quot;color: red;&quot;>[myurl]</b> to insert your gallery URL if set in Piwigo\'s configuration options.
<br/><br/>
To use multiple languages, you can use the Extended description plugin\'s tags if it is active.';
?>