#-----------------------------------------------------------------------------
# Perl source generated by wxDesigner from file: global_settings.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

use Wx;
use strict;

use Wx qw( wxDefaultSize wxDefaultPosition wxID_OK wxID_SAVE wxID_SAVEAS wxID_CANCEL wxID_YES wxID_EXIT wxID_ABOUT wxID_HELP );
use Wx qw( wxVERTICAL wxHORIZONTAL wxALL wxLEFT wxRIGHT wxTOP wxBOTTOM wxCENTRE wxGROW wxADJUST_MINSIZE );
use Wx qw( wxALIGN_RIGHT wxALIGN_BOTTOM wxALIGN_CENTER wxALIGN_CENTER_VERTICAL wxALIGN_CENTER_HORIZONTAL );
use Wx qw( wxRA_SPECIFY_ROWS );

# Bitmap functions

use Wx qw( wxNullBitmap wxBITMAP_TYPE_PNG );

# Window functions

use vars qw($ID_TEXT); $ID_TEXT = 10000;
use vars qw($ID_GLOBAL_AUTHOR); $ID_GLOBAL_AUTHOR = 10001;
use vars qw($ID_GLOBAL_NAME_PREFIX); $ID_GLOBAL_NAME_PREFIX = 10002;
use vars qw($ID_GLOBAL_THUMB_SIZE); $ID_GLOBAL_THUMB_SIZE = 10003;
use vars qw($ID_GLOBAL_RESIZED_W); $ID_GLOBAL_RESIZED_W = 10004;
use vars qw($ID_GLOBAL_RESIZED_H); $ID_GLOBAL_RESIZED_H = 10005;
use vars qw($ID_GLOBAL_ROTATE); $ID_GLOBAL_ROTATE = 10006;
use vars qw($ID_GLOBAL_HIGH); $ID_GLOBAL_HIGH = 10007;

sub GlobalSettings {
    my( $item0 ) = Wx::BoxSizer->new( wxVERTICAL );
    
    my( $item1 ) = Wx::FlexGridSizer->new( 0, 2, 0, 0 );
    
    my( $item2 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Default author :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item2, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item3 ) = Wx::TextCtrl->new( $_[0], $main::ID_GLOBAL_AUTHOR, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item3, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item4 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Photo name  prefix :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item5 ) = Wx::TextCtrl->new( $_[0], $main::ID_GLOBAL_NAME_PREFIX, "", wxDefaultPosition, [400,-1], 0 );
    $item1->AddWindow( $item5, 0, wxALIGN_CENTER|wxALL, 5 );

    my( $item6 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Site thumbnail size :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item6, 0, wxALL, 5 );

    my( $item7 ) = Wx::TextCtrl->new( $_[0], $main::ID_GLOBAL_THUMB_SIZE, "", wxDefaultPosition, [80,-1], 0 );
    $item1->AddWindow( $item7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item8 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Site image width :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item9 ) = Wx::TextCtrl->new( $_[0], $main::ID_GLOBAL_RESIZED_W, "", wxDefaultPosition, [80,-1], 0 );
    $item1->AddWindow( $item9, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item10 ) = Wx::StaticText->new( $_[0], $main::ID_TEXT, "Site image height :", wxDefaultPosition, wxDefaultSize, 0 );
    $item1->AddWindow( $item10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item11 ) = Wx::TextCtrl->new( $_[0], $main::ID_GLOBAL_RESIZED_H, "", wxDefaultPosition, [80,-1], 0 );
    $item1->AddWindow( $item11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item12 ) = Wx::RadioBox->new( $_[0], $main::ID_GLOBAL_ROTATE, "Auto rotate image", wxDefaultPosition, wxDefaultSize, 
        ["Yes","No"] , 1, wxRA_SPECIFY_ROWS );
    $item1->AddWindow( $item12, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $item13 ) = Wx::RadioBox->new( $_[0], $main::ID_GLOBAL_HIGH, "Upload high (original size) ", wxDefaultPosition, wxDefaultSize, 
        ["No","Yes"] , 1, wxRA_SPECIFY_ROWS );
    $item1->AddWindow( $item13, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    $item0->Add( $item1, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    my( $set_size ) = @_ >= 3 ? $_[2] : 1;
    my( $call_fit ) = @_ >= 2 ? $_[1] : 1;
    if( $set_size == 1 ) {
         $_[0]->SetSizer( $item0 );
         
         if( $call_fit == 1 ) {
             $item0->SetSizeHints( $_[0] );
         }
    }
    
    $item0;
}

# Menu bar functions


# Toolbar functions


# End of generated file
